@hostname = localhost
@port = 8000
@host = {{hostname}}:{{port}}/api
@contentType = application/json

###

GET http://{{host}}/articles HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

###

POST http://{{host}}/articles HTTP/1.1
Authorization: Basic YWRtaW46cGFzc3dvcmQ=
Content-Type: {{contentType}}
Cache-Control: "no-cache"

{
    "title": "My {{$randomInt 1 10000}} article cool",
    "description": "Yo ~ {{$randomInt 1 10000}}",
    "content": "Total visits {{$randomInt 1 10000}} .",
    "author": {
        "firstname": "John {{$randomInt 100 1000}}",
        "lastname": "Validmer {{$randomInt 1 10}}",
        "age": {{$randomInt 20 130}},
        "email": "cooper.{{$randomInt 1 1000}}@localhost.com"
    }
}
